name: Permissions Only Workflow

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  skip-job:
    runs-on: ubuntu-latest
    steps:
      - name: Skip Job
        run: echo "Job skipped. Only permissions are set."
